# docker-compose.yml — определяет сервисы для разработки и тестирования.
    version: '3.8'

    services:
      # Настраиваем сервис для PostgreSQL
      db:
        image: postgres:15
        container_name: bank_cards_db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=bank_management
        # Открываем нужный порт (5432)
        ports:
          - "5432:5432"
        # Настраиваем volume для хранения данных (чтобы база не затиралась)
        volumes:
          - postgres_data:/var/lib/postgresql/data

    # Описываем volume, который создали выше
    volumes:
      postgres_data:
