server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  # 1. Настройки подключения к базе данных
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    username: postgres
    password: "1718"
    driver-class-name: org.postgresql.Driver

  # 2. Настройки Liquibase (управление миграциями)
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.xml
    enabled: true

  # 3. Настройки JPA / Hibernate
  jpa:
    open-in-view: false
    hibernate:
      # Важно: ставим 'validate', чтобы Hibernate проверял базу,
      # но не пытался менять её в обход Liquibase
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# 4. JWT настройки (исправлены в соответствии с JwtUtils.java)
bank:
  jwt:
    # Секретный ключ (должен быть длинным для алгоритма HS256)
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    # Время жизни токена (24 часа в миллисекундах)
    expirationMs: 86400000

# 5. Swagger / OpenAPI для документации API
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs